apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-basic-app
  namespace: argocd
 # finalizers:
 # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: nginx
    repoURL: https://github.com/shukerski/argocd-nginx-app
    targetRevision: HEAD
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true